### ISSUE TITLE
Remove randomness in csv line selection

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#100]

**Comment by Spygn** [comment]
First doing Ig Follower Collector, Ig Profile Scraper, Lk Auto Follow

**Comment by TASnomad** [comment]
# Todo List:
- CERE API
- LPV API
- LAE API
- E2 API

**Comment by TASnomad** [comment]
All APIs mentionned is this thread now a statefull process whitout randomness selection (see commits 
6d34088, 60853ca, 4b2b33c)
