### ISSUE TITLE
LinkedIn Search Export: handle more search results types

### ISSUE THREAD

**Issue by TASnomad** [phantombuster/api-store#102]
# Enhancement

For now the API can only handle search results

Todo:
- Handle Jobs results
- Handle Group results
- Handle Companies results
- Handle Schools results

~~PB user to notify: 4694~~

**Comment by paps** [comment]
Notify on closure:
- [Support thread](https://app.intercom.io/a/apps/iy2q5eeo/inbox/inbox/all/conversations/17689240323)
- http://disq.us/p/1ub75ui
