### ISSUE TITLE
Domain Name Finder: Getting yahoo.com via (Y) as a result instead of correct domain

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#103]

**Comment by TASnomad** [comment]
It seems that this bug is due the Yahoo rate limit.

Since Yahoo seems not reliable (see issue #48), we should remove it from the WebSearch library.

**Comment by paps** [comment]
[Related support thread](https://app.intercom.io/a/apps/iy2q5eeo/inbox/inbox/conversation/17679136433#part_id=comment-17679136433-1628512099)

**Comment by TASnomad** [comment]
Patch deployed (commit 108819)

User notify
