### ISSUE TITLE
Instagram Follower Collector

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#114]
Extract a list of all the profiles that follow any Instagram account.

- [x] Code
- [x] Hidden prod version deployed
- [x] Tutorial
  - [x] Basic step-by-step
  - [x] Growth-hacking blurb, strategy & tips
- [x] Settings
  - [x] Argument help link
  - [x] Inline help `(?)` links
- [x] Tests
- [x] Secret URL shared with beta testers
- [x] Prod version revealed and flagged as new
- [x] Newsletter sent

**Comment by 8669822009** [comment]
Hii

**Comment by 8669822009** [comment]
hoe to create an proper git hub account
