### ISSUE TITLE
LNB : Not correctly checking pending status

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#117]
[Support thread](https://app.intercom.io/a/apps/iy2q5eeo/inbox/inbox/conversation/17722637397#part_id=user-message-17722637397-237402779)

**Comment by Spygn** [comment]
#todo check connection validation afterwards (manage invitations page)

**Comment by TASnomad** [comment]
Patch deployed (5b68d2b)

Closing this issue. Reopen if the bug occurs one again
