### ISSUE TITLE
LI Accept Invitations: element "textarea.msg-form__textarea" not visible

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#118]
> * Spawning Node v8.5.0
> ℹ️ Fetching session cookie from global object at "linkedInCookie"
> 🔄 Connecting to LinkedIn...
> ✅ Connected successfully as Martin Tapia
> 🔄 Scrolling down...
> ❌ Error: wait until visible failure: exception thrown from page: waited 10020ms but element "textarea.msg-form__textarea" still not visible
> * Process finished with an error (exit code: 1) (Tue Jul 31 2018 12:15:42 GMT+0000 (UTC))

**Comment by TASnomad** [comment]
Fix deployed (c5ee7a1)
