### ISSUE TITLE
Add error detection in stateful APIs that select a number of lines per launch

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#119]
so that the erroneous lines aren't re-treated at each new launch.

**Comment by Spygn** [comment]
[Support thread](https://app.intercom.io/a/apps/iy2q5eeo/inbox/inbox/2244427/conversations/17935894952)

**Comment by TASnomad** [comment]
Fixed by @Spygn

**Comment by Spygn** [comment]
- [ ] LPV API 
- [ ] LAE API 
- [ ] E2 API 
- [ ] LCE API 
- [ ] IFlwrC API 
- [ ] IPS API
- [ ] LAF API 
- [ ] TAL API 
- [ ] LNB API
- [ ] LPS API

**Comment by TASnomad** [comment]
All APIs are now handling error detections on the stateful mechanism.

Reopen the issue, if APIs need more detections.
