### ISSUE TITLE
LinkedIn Profile Scraper: Cannot read property 'textContent' of null

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#12]
Reported by a friendly user

Could not scrape https://www.linkedin.com/in/amit-kudale-3302281b/ because: Error: evaluate: code evaluation failed: exception thrown from page: Uncaught (in promise) TypeError: Cannot read property 'textContent' of null

**Comment by TASnomad** [comment]
The commit 200541f provides a fix about the described bug.
Reopen this issue, if the bug stills happen.
