### ISSUE TITLE
Linkedin - Format JSON companiesUrl

### ISSUE THREAD

**Issue by seelixe** [phantombuster/api-store#126]
Hello, I try to run Linkedin Companies Employees but i have this error:
`❌ Could not scrape company [object Object] because TypeError: url.indexOf is not a function`

The crawler does not take the url as parameter.
I forgot a detail or maybe the crawler is not working to take `companiesUrl `parameter ?

My JSON on phantombuster:
```
{
"companiesUrl": [
	{
		"": "https://www.linkedin.com/company/.../"
	}
],
sessionCookie": "..."
}
```

**Comment by TASnomad** [comment]
Hello @seelixe,

The `companiesUrl` parameter doesn't contains objects but strings.

Configuration snippet:
```
"companiesUrl": [ "https://www.linkedin.com/company/.../", "https://www.linkedin.com/company/...../" ]
```

Regards

**Comment by seelixe** [comment]
Thank you @TASnomad !
