### ISSUE TITLE
LinkedIn Chat Extractor

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#135]
Extract X messages from any LinkedIn conversation

- [x] Code
- [x] Tutorial
  - [x] Basic step-by-step
  - [x] Growth-hacking blurb, strategy & tips
- [x] Settings
  - [ ] Argument help link
  - [ ] Inline help `(?)` links
- [x] Tests
- [x] Hidden prod version deployed
- [ ] Secret URL shared with beta testers
- [x] Prod version revealed and flagged as new
- [x] Newsletter sent

**Comment by TASnomad** [comment]
API released
