### ISSUE TITLE
Facebook Page Likers

### ISSUE THREAD

**Issue by Drax35c2db** [phantombuster/api-store#145]
**Get all the people who like a list of Facebook pages.**
- [x] Code
- [x] Hidden prod version deployed
- [x] Tutorial
  - [x] Basic step-by-step
  - [x] Growth-hacking blurb, strategy & tips
- [x] Settings
  - [x] Argument help link
  - [x] Inline help `(?)` links
- [x] Tests
- [x] Secret URL shared with beta testers
- [x] Prod version revealed and flagged as new
- [x] Newsletter sent

**Comment by PhantomBusterMehdi** [comment]
TODO: 
- CSV
- Get Image link
- Get friend status
- Limit liker number
