### ISSUE TITLE
LI API Error:  please open at least one tab

### ISSUE THREAD

**Issue by dplewis** [phantombuster/api-store#159]
The recent commit https://github.com/phantombuster/api-store/commit/fdd9bc5972e1e192ce5f2b21ae0e3f9199b2538d calls `tab.close()` after each iteration but throws the following errors

```
Could not get XYZ linkedIn profile because Error: this tab has finished its work (close() was called), no other actions can be done with it
```

```
Caught exception when saving session cookie: Error: getAllCookies: could not manipulate cookies because there are no open tabs, please open at least one tab
```

I can try to submit a PR if you want

**Comment by TASnomad** [comment]
Hello @dplewis,

Thanks for the bug report :)
I think it's okay, i just revert the mentionned commit.
