### ISSUE TITLE
LinkedIn Learning Likers

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#160]
Extract a list of profiles who liked a Linkedin learning course

- [x] Code
- [x] Hidden prod version deployed
- [x] Tests
- [x] Tutorial
  - [x] Basic step-by-step
  - [x] Growth-hacking blurb, strategy & tips
- [x] Settings
  - [x] Argument help link
  - [x] Inline help `(?)` links
- [ ] Secret URL shared with beta testers
- [x] Prod version revealed and flagged as new
- [x] Newsletter sent

**Comment by TASnomad** [comment]
API released
