### ISSUE TITLE
Google Search

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#161]
Get the first result of a Google search.

- [ ] Code
- [ ] Hidden prod version deployed
- [ ] Tutorial
  - [ ] Basic step-by-step
  - [ ] Growth-hacking blurb, strategy & tips
- [ ] Settings
  - [ ] Argument help link
  - [ ] Inline help `(?)` links
- [ ] Tests
- [ ] Secret URL shared with beta testers
- [ ] Prod version revealed and flagged as new
- [ ] Newsletter sent

**Comment by guillaumeboiret** [comment]
Jira
