### ISSUE TITLE
Facebook Audience Builder

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#163]
.

- [x] Code
- [x] Hidden prod version deployed
- [ ] Tutorial
  - [ ] Description
  - [ ] Basic step-by-step
  - [ ] Growth-hacking blurb, strategy & tips
- [x] Settings
  - [x] Argument help link
  - [x] Inline help `(?)` links
- [ ] Tests
- [ ] Logo
- [ ] Secret URL shared with beta testers
- [ ] Prod version revealed and flagged as new
- [ ] Newsletter sent

**Comment by guillaumeboiret** [comment]
https://app.intercom.io/a/apps/iy2q5eeo/users/5b5ab8040a9bb39559c9ab75/all-conversations

**Comment by guillaumeboiret** [comment]
Jira.
