### ISSUE TITLE
LinkedIn Message Followup

### ISSUE THREAD

**Issue by TASnomad** [phantombuster/api-store#169]
**Send a templated message minutes, hours or days after a new connection occured**

- [ ] Code
- [ ] Hidden prod version deployed
- [ ] Tutorial
  - [ ] Basic step-by-step
  - [ ] Growth-hacking blurb, strategy & tips
- [ ] Settings
  - [ ] Argument help link
  - [ ] Inline help `(?)` links
- [ ] Tests
- [ ] Secret URL shared with beta testers
- [ ] Prod version revealed and flagged as new
- [ ] Newsletter sent

**Comment by guillaumeboiret** [comment]
Jira
