### ISSUE TITLE
LinkedIn Sales Navigator Profile Scraper

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#173]
Profile Scraper of Sales Navigator profiles.

- [x] Code
- [x] Hidden prod version deployed
- [ ] Tutorial
  - [ ] Description
  - [ ] Basic step-by-step
  - [ ] Growth-hacking blurb, strategy & tips
- [ ] Settings
  - [ ] Argument help link
  - [ ] Inline help `(?)` links
- [x] Tests
- [ ] Logo
- [ ] Secret URL shared with beta testers
- [ ] Prod version revealed and flagged as new
- [ ] Newsletter sent

**Comment by guillaumeboiret** [comment]
Jira
