### ISSUE TITLE
Crunchbase Companies Info

### ISSUE THREAD

**Issue by josselinlbe** [phantombuster/api-store#174]
Get informations from a company on Crunchbase with a login (Overview, Funding Rounds, Investors, Acquisitions,  Current Team, Board Members and Advisors)

Optional additional details on how it's going to work.

- [ ] Code
- [ ] Hidden prod version deployed
- [ ] Tutorial
  - [ ] Description
  - [ ] Basic step-by-step
  - [ ] Growth-hacking blurb, strategy & tips
- [ ] Settings
  - [ ] Argument help link
  - [ ] Inline help `(?)` links
- [ ] Tests
- [ ] Logo
- [ ] Secret URL shared with beta testers
- [ ] Prod version revealed and flagged as new
- [ ] Newsletter sent

**Comment by guillaumeboiret** [comment]
Jira
