### ISSUE TITLE
All APIs: allow to rename result.csv, a column name and number of lines to process per launch

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#176]
- [x] Facebook Audience Builder
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [ ] Facebook Auto Liker
  - [x] Column Name
  - [x] Number of lines
  - [ ] CSV Name
- [x] Facebook Birthday Wisher
  - [x] CSV Name
- [x] Facebook Event Guests Exporter
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Facebook Group Extractor
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [ ] Facebook ID Finder
  - [ ] Column Name
  - [ ] Number of lines
  - [ ] CSV Name
- [x] Facebook Message Sender
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Facebook Network Booster
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [ ] Facebook Page Likers
  - [x] Column Name
  - [ ] Number of lines
  - [x] CSV Name
- [x] Facebook Post Commenters
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Facebook Post Likers
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Facebook Profile Scraper
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [ ] Facebook Profile URL Finder
  - [x] Column Name
  - [ ] Number of lines
  - [x] CSV Name
- [x] Instagram Auto Follow 
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Instagram Auto Liker
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Instagram Follower Collector
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Instagram Following Collector
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [ ] Instagram Hashtag Collector
  - [x] Column Name
  - [ ] Number of lines
  - [x] CSV Name
- [ ] Instagram Multi Hashtag Search
  - [x] Column Name
  - [ ] Number of lines
  - [x] CSV Name
- [x] Instagram Photo Likers
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Instagram Post Data Extractor
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Twitter Profile Scraper
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Twitter Likes Export
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Twitter Media Extractor
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Twitter Auto Follow
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name
- [x] Twitter Auto Liker
  - [x] Column Name
  - [x] Number of lines
  - [x] CSV Name

**Comment by guillaumeboiret** [comment]
Jira
