### ISSUE TITLE
Optimize AWS S3 $ costs 💸

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#200]
In order to reduce our AWS S3 usage, we need to do the following:
- [ ] **Only fetch files from storage when truly needed:**
  - [ ] Do not fetch files when the input is invalid
  - [ ] Do not fetch files when the cookie is invalid
  - [ ] Fetch files at the last possible moment, when the script is ready to go
- [ ] **Only save files to storage when truly needed:**
  - [ ] Do not save files when the result is identical to the input

**Comment by guillaumeboiret** [comment]
Jira
