### ISSUE TITLE
All APIs: Indentation is broken in many (most?) json files

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#202]
See for example:
https://github.com/phantombuster/api-store/blob/master/store/Domain%20Name%20Finder/Domain%20Name%20Finder.json
https://github.com/phantombuster/api-store/blob/master/store/Youtube%20Videos%20Extractor/Youtube%20Videos%20Extractor.json

It was decided that we use tabs to indent (and spaces to align if necessary). Most of our code respects this rule, it's great.

However our json files seem to very often be half spaces, half tabs. Please fix this! And please configure your editor :)

Useful line to find all json files using spaces instead of tabs: <pre>grep '    ' store/**/*.json -m 1</pre>

**Comment by TASnomad** [comment]
Broken identations should be fixed for most APIs.
Please reopen this issue if you discover new broken identations
