### ISSUE TITLE
StoreUtilities - Remove NickJS

### ISSUE THREAD

**Issue by guillaumeboiret** [phantombuster/api-store#206]
Change the constructor type by `public constructor(nick: Nick|unknown, buster: Buster)`
Replace `nick.exit();`  by `process.exit(1);`

**Comment by TASnomad** [comment]
DEV version of lib-StoreUtilities doesn't use anymore `nick`

**Comment by TASnomad** [comment]
Enhancement deployed on the commit a028a99
