### ISSUE TITLE
Product Hunt Profile Scraper

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#208]
- [x] Code
- [x] Hidden prod version deployed
- [ ] Tutorial
  - [x] Description
  - [x] Basic step-by-step
  - [x] Growth-hacking blurb, strategy & tips
- [x] Settings
  - [x] Argument help link
  - [x] Inline help `(?)` links
- [x] Tests
- [x] Logo
- [ ] Secret URL shared with beta testers
- [ ] Prod version revealed and flagged as new
- [ ] Newsletter sent

**Comment by guillaumeboiret** [comment]
Jira
