### ISSUE TITLE
Product Hunt Auto Follow

### ISSUE THREAD

**Issue by Spygn** [phantombuster/api-store#212]
- [x] Code
- [x] Hidden prod version deployed
- [ ] Tutorial
  - [ ] Description
  - [ ] Basic step-by-step
  - [ ] Growth-hacking blurb, strategy & tips
- [x] Settings
  - [x] Argument help link
  - [x] Inline help `(?)` links
- [ ] Tests
- [ ] Logo
- [ ] Secret URL shared with beta testers
- [ ] Prod version revealed and flagged as new
- [ ] Newsletter sent

**Comment by guillaumeboiret** [comment]
Jira
