### ISSUE TITLE
Scraping libraries should handle both NickJS & Puppeteer

### ISSUE THREAD

**Issue by TASnomad** [phantombuster/api-store#218]
Libs to update:
--

- [ ] lib-Facebook
- [ ] lib-LinkedIn
- [ ] lib-LinkedInScraper
- [ ] lib-GitHub
- [x] lib-Medium
- [ ] lib-ProductHunt
- [x] lib-Twitter
- [ ] lib-Instagram (only `login` method updated)
- [ ] lib-Slack
- [ ] lib-Youtube

**Comment by guillaumeboiret** [comment]
Jira
