### ISSUE TITLE
Twitter Auto Follow: Ability to filter profiles to follow by langs

### ISSUE THREAD

**Issue by TASnomad** [phantombuster/api-store#30]
Enhancement
---

Do not make the follow process if a twitter profile doesn't use a language given in a languages whitelist

```New script arguments```
- An array of langages

```Follow process```
- Check if the profile use a language in the whitelist

→ Notify PB user 3082 when job is done

**Comment by TASnomad** [comment]
__Update__
___
Twitter add to every tweets the language used (a tweet element have a field ```lang```)

The script should be able to detect if scraped languages are in a given whitelist

__Warning__
___ 
- For now it only works if __there are some tweets to scrape in the page__
- The profile must not be protected

**Comment by paps** [comment]
Todo:
 - remove loadAllTweets
 - schema update
 - tests
