### ISSUE TITLE
LinkedIn Network Booster: Nonunderstandable error when there are no more profiles to add in a result.csv 

### ISSUE THREAD

**Issue by guillaumeboiret** [phantombuster/api-store#36]
See logs of agent 6215 of user 2832

→ Notify PB user 2832

**Comment by TASnomad** [comment]
<img width="1222" alt="capture d ecran 2018-03-26 a 11 45 08" src="https://user-images.githubusercontent.com/14291908/37899385-aac4ea54-30eb-11e8-925c-dddc5d7352bc.png">

**Comment by paps** [comment]
@guillaumeboiret @TASnomad can we close this?
