### ISSUE TITLE
AngelList Market Companies: Ability to scrape any kind of startup listing

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#38]
Currently it's not working for https://angel.co/companies?markets[]=E-Commerce&raised[min]=2040355&raised[max]=100000000 for example

It should

→ Notify PB users 3938, 3985

**Comment by TASnomad** [comment]
Commit ffab41400d5778c7a5f31d98776d18e3929d6208 provides enhancements for this issue.

PB users 3938 & 3985 are notified
