### ISSUE TITLE
LinkedIn Search Export: currentJob is sometimes the past job

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#39]
> we get a column "current job"
> this is not always somebody's current job, as the scraper also gets this title when it is somebody's past job
> for instance, this goeds right:
> Current: Global Head of Pensions and Insurance at Kempen Capital Management
> for instance, this goes wrong: Past: Intern at Kempen & Co
> in both examples, "past"
>  and "current" is left out in the "current job" column
> so you cannot see the difference between current or past

![tmp](https://user-images.githubusercontent.com/319424/37973909-de887ea0-31db-11e8-97e3-313eeb67da08.png)

> Martijn's current job in the exported data is "Intern bij Kempen & Co", while this is not hist current job, but past job

→ Notify PB user 3902

**Comment by TASnomad** [comment]
Commit ebf8abac89da0a3b349ce54dbd378a46e467d8de provides a fix for the described bug in this issue.

PB user 3902 notified for this update.
