### ISSUE TITLE
lib-StoreUtilities: general improvements

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#4]

**Comment by TASnomad** [comment]
#todo
- Needle HTTP call 3 retries
- Better error messages, in order of test:
  - No rights for viewing Google Spreadsheet
  - HTTP codes: 404 etc
  - Not a CSV (use Papaparse errors to detect)
- Support `gid` parameter
- Handle drive link redirection like `https://drive.google.com/open?id=XXXX`

**Comment by TASnomad** [comment]
getDataFromCsv2 methods from lib-StoreUtilities implements improvements described in this issue.

Please reopen this issue, if it needs more workaround to do.
