### ISSUE TITLE
lib-LinkedInScraper: More than 3 skills + endorsement count

### ISSUE THREAD

**Issue by luappaul** [phantombuster/api-store#40]
Don't find a way to add others skills (not top skills flag) and endorsement count in my csv result

**Comment by paps** [comment]
Thanks for the issue. Just so you know, it's not our top priority right now, but we'll definitely try to do this at a later time.

**Comment by paps** [comment]
Todo
 - fields `skillX`, `endorsementsX` (max X constant, 6 for now)
 - `+99` as is
