### ISSUE TITLE
Insta Hashtag Collector: Make # mandatory for hashtag search, support location search without #

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#43]

**Comment by paps** [comment]
Todo
 - Forge URL for hashtag search, use autocomplete dropdown for location search

**Comment by TASnomad** [comment]
The 2 commits: 437c5514c9883703fe6f74b9bb57e73af3595e7e, 35d78ad2e94166254b9d02d0710dd27daa4bffbb are providing the enhancement described in this issue.

If it needs more improvements, feel free to reopen this issue.
