### ISSUE TITLE
Insta scraper APIs: Count occurences of hashtags/locations

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#45]
At the end of an Instagram scraping run, go through 100% of the post texts and extract every hashtag. Then count the total number of occurences of each hashtag, globally.

Do the same for locations.

The goal is to make the user discover which hashtag he should use in his next search.

What's the best way to return this to the user?
- Append to end of output CSV?
- Other CSV alongside output? (but then we need to ask its name...)

**Comment by guillaumeboiret** [comment]
Jira
