### ISSUE TITLE
Twitter APIs: On each profile visit, check if still logged in

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#46]
In some cases, if the user's cookie becomes invalid during the API run, we continue looping through all the input lines without stopping. This consumes all the user's execution time, we shouldn't do that.

→ Notify PB user 3697

**Comment by TASnomad** [comment]
lib-Twitter has now the method `isLogged` (commit: cb760662f52369bbe95cb850d8a17fbb4d12513f)

Twitter APIs should use it
