### ISSUE TITLE
LinkedIn Auto Withdraw: Fix to better handle new LinkedIn UI for withdrawing invites

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#5]
https://phantombuster.com/api-store/3672/linkedin-auto-withdraw

**Comment by guillaumeboiret** [comment]
Extract and save withdrawn profiles' URL.

**Comment by guillaumeboiret** [comment]
I set the API in hidden mode.

**Comment by paps** [comment]
Fixed by @TASnomad 

API not hidden anymore
