### ISSUE TITLE
LinkedIn Companies Info: Collect related companies

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#57]
> As new columns: Company 1 Linkedin URL, Company 1 name, Company 1 sector, Company 1 Employee Range and the same for Company 2,3,4,5,6 (there are usually 6 companies) so 24 new columns total.

> It's a matter of selecting the correct `<section>` with the `.org-similar-orgs` CSS class. Then iterate over all `<li>` within it

![image](https://user-images.githubusercontent.com/319424/39242833-c58dda82-488b-11e8-803f-c35366ce99c5.png)

→ Notify PB user 4849

**Comment by TASnomad** [comment]
The commit 3cc4dc1 provides a handler to extract the data described in this issue.
This enhancement is for now only used into the DEV version of the API.

Please reopen this issue if it needs work to do in this enhancement.
