### ISSUE TITLE
lib-LinkedIn: hasReachedCommercialLimit

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#58]
- Return error string or null instead of boolean
- Forge error string but return default string if not possible
- use it on Companies Employees and Search Export

**Comment by TASnomad** [comment]
Commits 1251a73, 7cef00d make lib-LinkedIn method `hasReachedCommercialList` reliable.
Those commits also patch dev version of `LinkedIn Search Export` & `LinkedIn Companies Employees` with a better use of the lib.

Reopen this issue, if it stills work to do.
