### ISSUE TITLE
Failure to execute the API LinkedIn Follower Insights

### ISSUE THREAD

**Issue by AstridSeulliet** [phantombuster/api-store#62]
When I launch the agent, the script shows an error:

----- New Launch -----
* Container 24342732 started in azu-us-west-or-botrunner-2 (Sun May 13 2018 20:21:48 GMT+0000 (UTC))
* Got dependency LinkedIn Followers Insights.js
* Got dependency lib-LinkedIn.js
* Got dependency lib-StoreUtilities.js
* Spawning Node v8.5.0
🔄 Connecting to LinkedIn...
✅ Connected successfully as Astrid Seulliet
❌ Error: wait until visible failure: exception thrown from page: waited 5045ms but element "ul.feed-following-list" still not visible
* Process finished with an error (exit code: 1) (Sun May 13 2018 20:22:01 GMT+0000 (UTC))

**Comment by TASnomad** [comment]
Hello @AstridSeulliet,

Thank you for the issue,

The API wasn't able to handle accounts which don't have any followers.
Now it's patched.
If the bug still appearing, please reopen this issue, or create a new one.

Regards,
