### ISSUE TITLE
Twitter Follow(er/ing) Collector: API stops too early

### ISSUE THREAD

**Issue by paps** [phantombuster/api-store#75]
When a Twitter account has a large number of followers, the API seems to stops around 5000 collected followers. Probably missing some retries in case of errors.

Todo:
 - Switch to use package 5
 - Add logging info to debug
 - Make scrolling loop more resilient to failure, fix problem
 - Remove debugging info

Example of pages that trigger a problem:
 - `@jaysondemers`
 - `@contently`

Users 2969, 6428 have the problem.

→ Notify PB user 2969, 6428

**Comment by TASnomad** [comment]
The Twitter Follower Collector API seems to have another bug:

The API can fail at the first scrolling into `profile/followers` page,
(CSV only get 18 followers when the bug appears)

Todo:
 - Find a  __reliable__ loading procedure when scrolling into `/followers` page

PB user 6356 got this problem

→ Notifiy PB user 6356

**Comment by TASnomad** [comment]
Patch is now in the API-Store (see commit 8690d4e).
PB users 6356, 2969, 6428 are notified about this patch.
