### ISSUE TITLE
LinkedIn Search Export: Not handled error + result export fails

### ISSUE THREAD

**Issue by guillaumeboiret** [phantombuster/api-store#87]
→ Notify PB user 7030

An error is not handled plus the result file is not created before the API crashes.

🔄 Getting infos for search https://www.linkedin.com/search/results/people/?facetCurrentCompany=%5B%22443994%22%5D&origin=FACETED_SEARCH&title=(VP%20OR%20Gerente%20OR%20Director%20OR%20Vice%20OR%20CEO)%20AND%20(Operations%20OR%20Logistics%20OR%20Marketing%20OR%20Operaciones%20OR%20Logistica) ...
🔄 Getting infos from page 1...
❌ Error: wait until visible failure: exception thrown from page: waited 5027ms but elements div.search-no-results__container, div.search-results-container still not visible
* Process finished with an error (exit code: 1) (Thu Jun 21 2018 16:53:08 GMT+0000 (UTC))

**Comment by TASnomad** [comment]
Commit 44acc14 should fix the described bug
