### ISSUE TITLE
lib-LinkedInScraper: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by cgaspoz** [phantombuster/api-store#88]
It seems that an error in scraping the skills is not handled and prevents saving the profile

🔄 Opening page https://www.linkedin.com/in/mario-willa-b5011087
✅ Profile loaded.
🔄 Scrolling to load all data of the profile...
✅ All data loaded
🔄 Scraping page...
✅ https://www.linkedin.com/in/mario-willa-b5011087 successfully scraped.
⚠️ Can't scrape the profile at https://www.linkedin.com/in/mario-willa-b5011087 due to: Cannot read property 'name' of undefined

**Comment by TASnomad** [comment]
Hello @cgaspoz,

Thank you for submitting this issue :)
This issue was affecting LinkedIn Profile Scraper API, when creating the CSV output.
It should be fixed.

Can you tell me, if you can reproduce this error with the new patch ?

Regards,
