### ISSUE TITLE
LinkedIn Search Export Sales Navigator

### ISSUE THREAD

**Issue by TASnomad** [phantombuster/api-store#97]
PB User to notify when released: 6044 and 7568

**Comment by Spygn** [comment]
Export a Sales Navigator search result.

- [x] Code
- [ ] Tutorial
  - [x] Basic step-by-step
  - [ ] Growth-hacking blurb, strategy & tips
- [x] Hidden prod version deployed
- [ ] Settings
  - [x] Argument help link
  - [x] Inline help `(?)` links
- [x] Tests
- [ ] Secret URL shared to beta testers
- [ ] Prod version revealed and flagged as new
- [ ] Newsletter sent
